### ISSUE TITLE
建议：希望在恢复整个 session 或整个标签组的时候，以休眠的方式恢复多个标签页

### ISSUE THREAD

**Issue by fengpanhe** [one-tab-group/onetab.group#1]
就是涉及多个标签的恢复时，不直接打开页面，而只是恢复标签，就是当切换到那个标签才会刷新。

**Comment by xiaoluoboding** [comment]
@fengpanhe 嗯嗯，我也正打算做这个功能，感谢建议。

**Comment by TailendWong** [comment]
我觉得这个功能结合Suspender插件，已经实现了。将已经挂起的标签页拖进标签组就行了，如图，baidu的网址已经变成`chrome-extension://noogafoofpebimajpfpamcfhoaifemoa/suspended.html#ttl=%E7%99%BE%E5%BA%A6%E4%B8%80%E4%B8%8B%EF%BC%8C%E4%BD%A0%E5%B0%B1%E7%9F%A5%E9%81%93&pos=0&uri=https://www.baidu.com/`
[![vfGMsP.png](https://s1.ax1x.com/2022/08/29/vfGMsP.png)](https://imgse.com/i/vfGMsP)

**Comment by fengpanhe** [comment]
> 可以实现一部分吧，但是需要 suspender 先休眠才行，如果没有休眠的进入了 one tap 还是不行

**Comment by TailendWong** [comment]
是的

**Comment by xiaoluoboding** [comment]
v0.4.0 已经实现该功能，请更新后尝试

## Tips

在 `用户设置` 中，选择 `恢复且暂停`

![CleanShot 2022-09-25 at 22 28 14@2x](https://user-images.githubusercontent.com/6118824/192148956-0886ad01-c6fa-4781-b303-ca64354c0861.png)

同时支持了暂停当前打开的标签页
