### ISSUE TITLE
[BUG] stuck at the load page

### ISSUE THREAD

**Issue by RobinTsai** [one-tab-group/onetab.group#107]
The New version alway stuck at this page. 

date: 2023-12-13

![image](https://github.com/one-tab-group/onetab.group/assets/14065641/d973e2d7-930b-4ed6-b615-236c61005d98)

**Comment by xiaoluoboding** [comment]
> The New version alway stuck at this page. 
> 
> 
> 
> date: 2023-12-13
> 
> 
> 
> ![image](https://github.com/one-tab-group/onetab.group/assets/14065641/d973e2d7-930b-4ed6-b615-236c61005d98)
> 
> 

Hello, Can you provide the browser you are using and the version.

**Comment by RobinTsai** [comment]
![image](https://github.com/one-tab-group/onetab.group/assets/14065641/653c147b-49a1-4811-a7f7-184c3a768503)

**Comment by xiaoluoboding** [comment]
> ![image](https://private-user-images.githubusercontent.com/14065641/290174104-653c147b-49a1-4811-a7f7-184c3a768503.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0Njg1NTAsIm5iZiI6MTcwMjQ2ODI1MCwicGF0aCI6Ii8xNDA2NTY0MS8yOTAxNzQxMDQtNjUzYzE0N2ItNDlhMS00ODExLWE3ZjctMTg0YzNhNzY4NTAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDExNTA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxZTFlMjU2M2U0ZDRlOWU4ZmE5ZjVmNzk3MTk1NmQ3MDM5YjI2NTExYTg5YTJlNTUyMTM0ZmFmOTVjZDgxNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kQGlBHIx9KCu5lKnMDxMGhBFu4sngA_mbTGa2QNUoKg)

OK, I will keep track of this issue.

**Comment by xiaoluoboding** [comment]
We have resolved this issue, Please update the extension to version 2.1.2 and try again.
