### ISSUE TITLE
会话面板出不来

### ISSUE THREAD

**Issue by stimw** [one-tab-group/onetab.group#109]
<img width="1707" alt="image" src="https://github.com/one-tab-group/onetab.group/assets/30977647/44171182-668d-4358-a29d-d18aaa5be578">

已付费，开启了云同步。

猜测是服务器连不上，一直在转圈。

然后刷新的话会话面板一闪而逝。麻了。。我觉得如果timeout的话应该直接显示local的内容吧？而不是一直在请求转圈。
<img width="611" alt="image" src="https://github.com/one-tab-group/onetab.group/assets/30977647/6e159e23-2048-4538-bb40-8171ed442bc2">

**Comment by xiaoluoboding** [comment]
已知问题，感谢反馈，在修复了。

**Comment by xiaoluoboding** [comment]
@stimw 可以更新下试试， Version: 2.1.2

**Comment by stimw** [comment]
> @stimw 可以更新下试试， Version: 2.1.2

ok已恢复
