### ISSUE TITLE
cannot log in

### ISSUE THREAD

**Issue by z7skr** [one-tab-group/onetab.group#112]
I can log in at chrome, but not at edge.
It keep logging in ......

**Comment by z7skr** [comment]
with github account

**Comment by xiaoluoboding** [comment]
@z7skr Please use Chrome Extension on Edge browser, download it from here:

https://chromewebstore.google.com/detail/one-tab-group-tabtab-grou/lajbajamkpmkmldodfbljkjihppdclbm
