### ISSUE TITLE
Bug: Blank tab

### ISSUE THREAD

**Issue by abhimanyusinghgaur** [one-tab-group/onetab.group#12]
Sometimes, when I do `Open n tabs with Group` from a saved session, some of the opened tabs don't really have any URL in their address bar. They have: `about:blank`. In preferences, I have configured `Restore All Tabs / Tab Groups` as `Restore & Suspend`.

This happens on a random basis. Sometimes, all the tabs open correctly, sometimes they don't. Closing the tab group and reopening it again from onetab, sometimes solves the problem, but sometimes doesn't. Weird!

**Comment by abhimanyusinghgaur** [comment]
BTW, love the idea of directly using the chrome built-in tab groups, instead of creating your own. All other extensions just seem to create their own tab groups, which is what made me go for this extension.

I was doing something similar to you around 4 years ago. Not sure, if you might get any ideas from here: https://github.com/abhimanyusinghgaur/ChromeControlPanel

**Comment by xiaoluoboding** [comment]
> Sometimes, when I do `Open n tabs with Group` from a saved session, some of the opened tabs don't really have any URL in their address bar. They have: `about:blank`. In preferences, I have configured `Restore All Tabs / Tab Groups` as `Restore & Suspend`.
> 
> This happens on a random basis. Sometimes, all the tabs open correctly, sometimes they don't. Closing the tab group and reopening it again from onetab, sometimes solves the problem, but sometimes doesn't. Weird!

Can you tell me how many tabs you have open at the same time?

**Comment by abhimanyusinghgaur** [comment]
I have 7 tabs inside that tab group. It doesn't matter whether there are already any open tabs in my browser or not. It happens on a random basis. The last time I tried, there were 7-8 other tabs already open apart from that tab group.

**Comment by xiaoluoboding** [comment]
I have reproduced this bug and will fix it in the next release. Thanks a lot.

**Comment by abhimanyusinghgaur** [comment]
Update: I have opened the above two as separate issues: #13, #14. Thanks!
