### ISSUE TITLE
Enhancement: Tab group expand/collapse

### ISSUE THREAD

**Issue by abhimanyusinghgaur** [one-tab-group/onetab.group#14]
It would be really nice to expand/collapse a tab group just by clicking on it anywhere and not specifically on the expand/collapse button at the very end of the screen. It gets annoying to have to move the cursor to the very right of the screen in order to expand any tab group. You can still keep the drag and drop on the whole horizontal empty space on a tab group, but make it work only when someone is actually doing drag & drop. When someone is just clicking, on the empty horizontal space, you can make it expand/collapse.

**Comment by xiaoluoboding** [comment]
> It would be really nice to expand/collapse a tab group just by clicking on it anywhere and not specifically on the expand/collapse button at the very end of the screen. It gets annoying to have to move the cursor to the very right of the screen in order to expand any tab group. You can still keep the drag and drop on the whole horizontal empty space on a tab group, but make it work only when someone is actually doing drag & drop. When someone is just clicking, on the empty horizontal space, you can make it expand/collapse.

You can `double-click` on the `tab group` header bar, it will trigger the expand/collapse action.

In fact, that this feature is available now, it may be a bit difficult to find it or fit your habits.

I use double-click instead click on anywhere, and some to the `session`, double-click session header bar will trigger expand/collapse action.

**Comment by abhimanyusinghgaur** [comment]
Ah! I see. `double-click` is already there. I wasn't aware.

TBH, between the `click` and `double-click`, I find `click` to be more intuitive for expand/collapse behavior.

Every major framework makes it work on `click`, here are a few examples:
* https://materializecss.com/collapsible.html
* https://getbootstrap.com/docs/4.0/components/collapse/#accordion-example
* https://coreui.io/vue/docs/components/accordion.html
* https://bootstrap-vue.org/docs/components/collapse

**Comment by xiaoluoboding** [comment]
Already support it with `double-click`, I will close this issue
