### ISSUE TITLE
Chinese Searching not supported

### ISSUE THREAD

**Issue by yehudi-dev** [one-tab-group/onetab.group#17]
Can only search use English, not support of Chinese search.
Is it possible to support chinese keyword searching?

**Comment by xiaoluoboding** [comment]
I can't reproduce it.

<img width="1129" alt="CleanShot 2022-10-08 at 13 44 41@2x" src="https://user-images.githubusercontent.com/6118824/194691110-1e702b82-f479-49e8-9583-de1700299c84.png">
