### ISSUE TITLE
Loving it so far just a few ideas that may help.

### ISSUE THREAD

**Issue by JaxGray10** [one-tab-group/onetab.group#25]
- Being able to update a session instead of having to create a new one all the time.
- Being able to delete multiple sections at once.

**Comment by xiaoluoboding** [comment]
> Being able to update a session instead of having to create a new one all the time.

I will provide an option to control the behavior when you declutter your tabs

you can choose the options:

* Sending to the latest session
* Sending to a new session

sth like that.

**Comment by xiaoluoboding** [comment]
> Being able to delete multiple sections at once.

Will support the feature.

**Comment by JaxGray10** [comment]
Perfect thanks for listening!

**Comment by xiaoluoboding** [comment]
Supported in v1.0.0
