### ISSUE TITLE
Autogrpup tabs by domain

### ISSUE THREAD

**Issue by steve-agl** [one-tab-group/onetab.group#26]
I'd love to have new tab autoassigned to a group based on group rule (lie acid tab extension) so to have a single or multiple domain, or a series of wors that match into url, get automatically assigned to a group

**Comment by xiaoluoboding** [comment]
Good idea, I planned the feature already.

Stay tuned.

**Comment by xiaoluoboding** [comment]
Supported in v1.0.0
