### ISSUE TITLE
这玩意出bug了！某次打开我的标签全没了！

### ISSUE THREAD

**Issue by crysishacker** [one-tab-group/onetab.group#3]
fxxxck！！！！为什么？？

**Comment by crysishacker** [comment]
我去！我刚刚复现了它！我开了两个窗口（对应两组session），然后我打开这个扩展，就有两个扩展标签页
但是新的标签页什么都没！
旧的标签页刷新，记录就全没了！这么严重的bug！

**Comment by xiaoluoboding** [comment]
> fxxxck！！！！为什么？？

我觉得没必要出现 F 字眼吧，非常感谢您的 issue，帮忙提交的 bug。也请文明用语。

另外，插件提供了备份功能，请善用。
