### ISSUE TITLE
click on tabbed icon and you loose all your sessions and groups !

### ISSUE THREAD

**Issue by jerome-diver** [one-tab-group/onetab.group#32]
Improve your UI design because when i clicked on the tabbed extention icon on tool bar's web browser, i loosed all sessions and ggroup created (that's terrible loose of time that make me go far from your extention). 
By which logic it should be fine to loose all the sorting work and tabs opened by a simple click on an icon ? It is definitely stupid and counter productive.
There is some good ideas to have sessions and groups that can embed groups in a kind of tree organisation way, but without a safe and efficient UI design, it becomes unsafe and un-usable. It looks like an other one chinese gadget not finalized with lake of concern on absolute user's concerned priorities.

**Comment by xiaoluoboding** [comment]
There are a thousand Hamlets in a thousand people's eyes.

You think you have some good ideas, Maybe...

Please don't discuss things with prejudice.

It will only make people feel disgusted.

**Comment by jerome-diver** [comment]
You missed the point: the idea is to understand priority and test device UI design prior to publicate something. I just loose my open tabs because of your extention (who, again, has some good ideas inside). But it seems that you are unable to accept (for any ego reason) any constructive critics. No prejudice there, just facts. And don't be offusqued by chinese part criticise, because it is also a fact that your instruction show your down point (include your proble to accept critics).
