### ISSUE TITLE
Chrome naming for tab groups via one-tab

### ISSUE THREAD

**Issue by loa1962** [one-tab-group/onetab.group#60]
Hi, I love to work with multiple tab groups that I prefer to name like this for example:

![image](https://user-images.githubusercontent.com/45047854/215372251-b8a57cf1-f410-442e-a1fa-60cc597ade9c.png)

The tab group named FORUMS and EXT GPU with all capital letters are from me.

Can you please include it as a feature that you rename the tab group when restoring it with the name that we assign to it when saving it?

So for example I have a tabgroup that I would name GPU RESEARCH in one-tab and then when restoring the tabgroup the name of the group in my taskbar is also GPU RESEARCH - that would be very cool and nobody else has this feature!

If it is a technical impossibility please let me know but if not you should implement this asap as people with big and numerous tab groups will certainly appreciate it and they are your number one customers.

**Comment by xiaoluoboding** [comment]
Sorry for the late reply.

I have done some research on this requirement, and it seems that there is no way to change the group name in the taskbar.
