### ISSUE TITLE
Bug report:

### ISSUE THREAD

**Issue by barrrricade** [one-tab-group/onetab.group#61]
Browser: Brave [Version 1.46.153 Chromium: 108.0.5359.128 (Official Build) (64-bit)]
OS: Win 10 LTSC N

UI/UX:
- Trash, bubble, pin icon clickable area needs to be bigger. (often misclick)
- Needs checkbox for links within a session folder. (imported from onetab and needs cleanup but only one session)
- Hovering on 'Delete from session' dialog after hovering trash icon does not hide dialog
- - Cannot quickly delete multiple links upwards

Bug:
Cannot click on Trash, bubble, pin icon after using filter

**Comment by xiaoluoboding** [comment]
We will improve the UI and filter feature, thanks for your suggestion.
