### ISSUE TITLE
Notion

### ISSUE THREAD

**Issue by CallMeSteven1958** [one-tab-group/onetab.group#62]
I have tried several times following the Notion guide (https://www.onetab.group/blog/sync-your-browser-tabs-to-notion), but One Tab tries to connect but hangs. The blue bar moves 3/4 along, then stops!

Is this a known bug ?  (Definitely using the correct id/token)

Other than the above, great extension, thank you.

Thanks
steven.muster@gmail.com
g4uol@outlook.com

**Comment by xiaoluoboding** [comment]
Hey Steven,

Thank you for taking the time to reach out to us. We apologize for the issues you have been experiencing while trying to sync your browser tabs with Notion.

I haven't been able to reproduce this bug, I believe there must be something wrong somewhere. Could you provide us with more information, such as recording a video or taking a screenshot?

If there are any privacy issues, you can email them to our email address.

We are glad that you are enjoying One Tab Group and thank you for your continued support.

Regards,
One Tab Group Team

**Comment by CallMeSteven1958** [comment]
Hello

 

Thanks for a fast reply.

 

Attached is the screenshot from Edge. I don’t have anything to hide…so you can see my id from Notion plus my tabs, no problem.

 

Google sync appears to work – although where does it save it on Drive??

 

If I cannot get Notion to work, it’s not a major issue, but it be would be great if there was an automatic backup to Google Drive, maybe every 24 hours.

 

Best regards

 

Steven

**Comment by CallMeSteven1958** [comment]
Notion is slow but now working. The only item missing is the automatic backup of tabs via the cloud. Is this being planned?

**Comment by xiaoluoboding** [comment]
@CallMeSteven1958 Automatic backups are in the our roadmap

**Comment by CallMeSteven1958** [comment]
Great! ThanksSent from Outlook for Android
