### ISSUE TITLE
Github login error

### ISSUE THREAD

**Issue by chareasy** [one-tab-group/onetab.group#63]
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/2543886/217828483-9d4b51d2-a4cd-423d-9afc-88483176f6e7.png">

**Comment by chareasy** [comment]
Mac、Google Chrome 版本 109.0.5414.119

**Comment by chareasy** [comment]
Mac、Google Chrome 版本 109.0.5414.119

**Comment by xiaoluoboding** [comment]
Reloading the extension can be fixed this issue. We will improve the thrid-party login logic
