### ISSUE TITLE
Dragging links/tabs not working as expected

### ISSUE THREAD

**Issue by Crunchbits** [one-tab-group/onetab.group#75]
Unable to drag open tabs from the left to any session unless the session already has 4 links and I can only drag it anywhere below the top 4 links. Also dragging a link from a session to the left menu to open does not work 90% of the time.

**Comment by xiaoluoboding** [comment]
Thank you for bringing this issue to my attention.

I will fix the first issue

Regarding the second issue, we did not provide the feature that you can drag a link from a session to the left menu to open.
