### ISSUE TITLE
标签全部丢失

### ISSUE THREAD

**Issue by LengGeng** [one-tab-group/onetab.group#79]
原本存储的标签全部丢失，有办法找回吗

**Comment by xiaoluoboding** [comment]
Sorry, 没办法，请做好备份

**Comment by Saarsk** [comment]
Google translate for English readers (disclaimer: Google Translate often makes mistakes):
Title: _Label is all lost_

Comment 1 by LengGeng: _All the originally stored labels are lost, is there a way to retrieve them?_

Comment 2 by xiaoluoboding: _Sorry, no way, please make a backup_
